on: 
  workflow_dispatch:

name: build_osrm_and_prepare_graph

jobs:
  build_osrm_and_prepare_graph:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'Project-OSRM/osrm-backend'
          path: 'osrm-backend'

      - name: Get osrm-backend ref
        id: osrm-backend-ref
        run: |
          echo "::set-output name=ref::$(git -C osrm-backend rev-parse HEAD)"
        shell: bash

      - name: Cache osrm-backend/build
        id: cache_osrm_backend_build
        uses: actions/cache@v2
        with:
          path: |
            osrm-backend/build
          key: ${{ runner.os }}-${{ steps.osrm-backend-ref.outputs.ref }}-v1

      - name: Build osrm-backend
        if: steps.cache_osrm_backend_build.outputs.cache-hit != 'true'
        run: |
          cd osrm-backend
          mkdir build
          cd build
          cmake ../ -DENABLE_MASON=1
          make
          cd ../../
        shell: bash

      - name: Fetch OSM
        run: |
          curl -LJ https://github.com/stupidpupil/wales_ish_otp_graph/releases/latest/download/gtfs_and_osm.zip -o gtfs_and_osm.zip
          unzip gtfs_and_osm.zip
        shell: bash

      - name: Cache OSRM graph
        id: cache_osrm_graph
        uses: actions/cache@v2
        with:
          path: |
            *.osrm
          key: ${{ runner.os }}-${{ steps.osrm-backend-ref.outputs.ref }}-{{ hashFiles('gtfs_and_osm/*.osm.pbf') }}-v1

      - name: Process OSM
        run: |
          cat "disk=/tmp/stxxl,10G,syscall" > .stxxl
          ln -s osrm-backend/profiles/lib lib
          osrm-backend/build/osrm-extract -p osrm-backend/profiles/car.lua gtfs_and_osm/*.osm.pbf
          osrm-contract *.osrm




