on: 
  workflow_dispatch:

name: build_osrm

jobs:
  build_osrm:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'Project-OSRM/osrm-backend'
          path: 'osrm-backend'

      - name: Get osrm-backend ref
        id: osrm-backend-ref
        run: |
          echo "::set-output name=ref::$(git -C osrm-backend rev-parse HEAD)"
        shell: bash

      - name: Cache osrm-backend/build
        id: cache_osrm_backend_build
        uses: actions/cache@v2
        with:
          path: |
            ~/osrm-backend/build
          key: ${{ runner.os }}-${{ steps.osrm-backend-ref.outputs.ref }}-v1

      - name: Build osrm-backend
        #if: steps.cache_osrm_backend_build.outputs.cache-hit != 'true'
        run: |
          cd osrm-backend
          mkdir build
          cd build
          cmake ../ -DENABLE_MASON=1
          make

      - name: Test ls
        run: |
          ls -l ~